version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elibrary_app
    restart: always
    working_dir: /var/www
    volumes:
      - elibrary_vol:/var/www
      - ./public/covers:/var/www/public/covers
    depends_on:
      - db
    networks:
      - elibrary_net
    expose:
      - "9000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=elibrary
      - DB_USERNAME=root
      - DB_PASSWORD=Elibrary2025!

  db:
    image: mysql:8
    container_name: elibrary_db
    restart: always
    environment:
      - MYSQL_DATABASE=elibrary
      - MYSQL_ROOT_PASSWORD=Elibrary2025!
    ports:
      - "3306:3306"
    networks:
      - elibrary_net
    volumes:
      - ./db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: elibrary_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - elibrary_vol:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - elibrary_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: elibrary_phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=Elibrary2025!
      - UPLOAD_LIMIT=300M
    ports:
      - "9999:80"
    depends_on:
      - db
    networks:
      - elibrary_net

networks:
  elibrary_net:

volumes:
  elibrary_vol:
