# .github/workflows/build.yml
name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/elibrary:latest -t ghcr.io/${{ github.repository_owner }}/elibrary:${{ github.run_number }} .

      - name: Push Docker images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/elibrary:latest
          docker push ghcr.io/${{ github.repository_owner }}/elibrary:${{ github.run_number }}
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /root/elibrary
            docker-compose pull
            docker-compose down -v
            COMPOSE_HTTP_TIMEOUT=300 docker-compose up -d

